language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - ruby-head
  - jruby-1.7.19
  - jruby-head
env: JRUBY_OPTS=--2.0
gemfile:
  - gemfiles/Gemfile.activesupport-3.2.x
  - gemfiles/Gemfile.activesupport-4.0.x
  - gemfiles/Gemfile.activesupport-4.1.x
  - gemfiles/Gemfile.activesupport-4.2.x
  - gemfiles/Gemfile.activesupport-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.activesupport-edge
    - rvm: ruby-head
    - rvm: jruby-head
