language: ruby
rvm:
  - 2.0.0
  - 2.1.3
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/Gemfile.activesupport-3.2.x
  - gemfiles/Gemfile.activesupport-4.0.x
  - gemfiles/Gemfile.activesupport-4.1.x
  - gemfiles/Gemfile.activesupport-4.2.x
  - gemfiles/Gemfile.activesupport-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.activesupport-edge
    - rvm: ruby-head
